import type { Metadata } from "next";
import "./globals.css";
import { Kalam } from "next/font/google";

const kalam1 = Kalam({
  weight: "400",
  subsets: ["latin"],
});
const kalam2 = Kalam({
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kalam1.className} ${kalam2.className} bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
